<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\ViewModel\BillingAddress;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Closure $classNames */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(BillingAddress::class);
?>
<div
    id="billing-address-section"
    class="<?= $classNames(['relative checkout-payment-method', $viewModel->isVirtualCart() ? 'mt-8' : 'mt-12']) ?>"
>
    <?= $block->getChildHtml() ?>
</div>
