<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var string $eHtmlAttr */
/** @var string $nonce */
/** @var Closure $eJs */
/** @var Closure $viewModelProvider */
/** @var BillingAddress $viewModel */
$viewModel = $viewModelProvider(BillingAddress::class);
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        Alpine.data('BillingAddressForm', () => ({
            form: null,
            validator: null,

            init() {
                this.form = this.$el;
                this.modifyFormAfterRender();
                this.stepStore.actionButton.isDisabled = true;
            },

            async handleBillingUpdate() {
                const isValid = await this.validator.revalidate();
                if (isValid) {
                    this.stepStore.actionButton.isDisabled = false;
                    htmx.trigger(document.body, 'mahxcheckout-billing-validated')
                }
            },

            handleBillingCancel(event) {
                htmx.trigger(event.target, 'mahxcheckout-billing-canceled')
                this.stepStore.actionButton.isDisabled = false;
            },

            handleCountryChange(event) {
                this.$dispatch(`mahxcheckout-${this.form.id}-country_id-changed`, { country: event.target.value })
            },

            modifyFormAfterRender() {
                this.$nextTick(() => {
                    this.focusOnFirstname();
                    this.applyValidation();
                });
            },

            focusOnFirstname() {
                this.form.elements.firstname.focus();
            },

            applyValidation() {
                this.validator = mahxCheckout.validator(Object.assign({
                    form: this.form,
                }, JSON.parse('<?= $eJs($viewModel->getValidationJson()) ?>')))
                this.addValidatorToPageNavigation(this.form.id, this.validator);
            },

            get stepStore() {
                return this.$store.checkoutStepStorage;
            },
        }));
    });
</script>
