<?php declare(strict_types=1);

use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingAddress;

/** @var Template $block */
/** @var string $eHtmlAttr */
/** @var string $nonce */
/** @var Closure $eJs */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var ShippingAddress $viewModel */
/** @var DesignThemeInfo $themeInfo */

$viewModel = $viewModelProvider(ShippingAddress::class);
$themeInfo = $viewModelProvider(DesignThemeInfo::class);
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    function ShippingAddressForm(form) {
        return {
            form: null,
            validator: null,

            init() {
                this.form = form || this.$el ;
                this.validator = mahxCheckout.validator(Object.assign({
                    form: this.form,
                }, JSON.parse('<?= $eJs($viewModel->getValidationJson()) ?>')));
                this.addValidatorToPageNavigation(this.form.id, this.validator);
            },
        };
    }
    <?php if($themeInfo->isHyvaTheme()): ?>
    document.addEventListener('alpine:init', () => {
        Alpine.data('ShippingAddressForm', ShippingAddressForm);
    });
    <?php endif; ?>
</script>
