<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingAddress;

/** @var Template $block */
/** @var string $eHtmlAttr */
/** @var string $nonce */
/** @var Closure $eJs */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var ShippingAddress $viewModel */
$viewModel = $viewModelProvider(ShippingAddress::class);
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        Alpine.data('ShippingAddressForm', () => {
            return {
                form: null,
                validator: null,

                init() {
                    this.form = this.$el;
                    this.validator = mahxCheckout.validator(Object.assign({
                        form: this.form,
                    }, JSON.parse('<?= $eJs($viewModel->getValidationJson()) ?>')));
                    this.addValidatorToPageNavigation(this.form.id, this.validator);
                },

                async estimateShippingMethods(event) {
                    const inputElement = event.target;
                    const inputName = inputElement.name;

                    if (await this.validateInput(inputElement)) {
                        htmx.trigger(document.body, `mahxcheckout-${this.form.id}-${inputName}-validated`);
                    }
                },

                async validateInput(input) {
                    <?php // If no validation exists for this field, consider it valid ?>
                    if (!this.validator.hasRuleExistForInput(input)) {
                        return true;
                    }

                    try {
                        return await this.validator.revalidateField(input);
                    } catch (error) {
                        console.error("Validation error:", error);
                        return false;
                    }
                },

                dispatchShippingAddressSaved(event) {
                    this.$dispatch('mahxcheckout-shipping-address-saved', { htmxEvent: event });
                },
            };
        });
    });
</script>
