<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingAddress;

/** @var Template $block */
/** @var string $nonce */
/** @var Esc $esc */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(ShippingAddress::class);
$themeInfo = $viewModelProvider->get(DesignThemeInfo::class);
?>
<script nonce="<?= $esc->htmlAttr($nonce) ?>">
    function ShippingAddressForm(form) {
        return {
            form: null,
            validator: null,

            init() {
                this.form = form || this.$el ;
                this.validator = mahxCheckout.validator(Object.assign({
                    form: this.form,
                }, JSON.parse('<?= $esc->js($viewModel->getValidationJson()) ?>')));
                this.addValidatorToPageNavigation(this.form.id, this.validator);
            },
        };
    }
    <?php if($themeInfo->isHyvaTheme()): ?>
    document.addEventListener('alpine:init', () => {
        Alpine.data('ShippingAddressForm', ShippingAddressForm);
    });
    <?php endif; ?>
</script>
