<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\Totals;

/** @var Template $block */
/** @var Esc $esc */
/** @var Closure $classNames */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(Totals::class);
$totals = $viewModel->getTotals();
$grandTotal = $viewModel->getGrandTotal();
$isHtmxOob = (bool)$block->getData('is_htmx_oob');
$htmxLoaderClasses = implode(' ', $viewModel->getHtmxLoaderClasses());
?>
<div
    id="checkout-totals-summary"
    class="relative"
    <?= $isHtmxOob ? 'hx-swap-oob="true"' : '' ?>
>
    <dl class="space-y-3">
        <?php foreach ($totals as $total): ?>
            <?php if ($total->code === 'grand_total') continue; ?>

            <div class="<?= $classNames(['total-item flex justify-between items-center', "item-{$total->code}"]) ?>">
                <dt class="title text-gray-600">
                    <?= /** @noEscape */ $total->label ?>
                </dt>
                <dd class="amount text-gray-800 font-medium">
                    <?= $viewModel->formatPrice($total->value) ?>
                </dd>
            </div>
        <?php endforeach; ?>

        <?php if ($grandTotal): ?>
            <div class="grand-total total-item border-t border-gray-300 pt-4 mt-4 flex justify-between items-center text-xl font-semibold">
                <dt><?= $esc->html(__('Order Total')) ?></dt>
                <dd><?= $viewModel->formatPrice($grandTotal->value) ?></dd>
            </div>
        <?php endif; ?>
    </dl>
    <div
        id="order-totals-loader"
        class="<?= $classNames(['htmx-indicator checkout-loader', $htmxLoaderClasses => $htmxLoaderClasses]) ?>"
    >
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
