<?php
/** @var string $eHtmlAttr */
/** @var string $nonce */
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        Alpine.data('OrderSummary', () => ({
            isCartItemsVisible: false,

            get cartItemsCollapseClass() {
                return this.isCartItemsVisible ? 'collapse-open' : 'collapse-close';
            },

            init() {
                this.isCartItemsVisible = this.store.isCartItemsVisible;
            },

            toggleCartItemsVisibility() {
                this.isCartItemsVisible = !this.isCartItemsVisible;
                this.store.isCartItemsVisible = this.isCartItemsVisible;
            },

            get store() {
                return this.$store.app.orderSummary;
            },
        }));

        Alpine.data('CartItem', () => ({
            isOptionsVisible: false,

            get optionsCollapseClass() {
                return this.isOptionsVisible ? 'collapse-open' : 'collapse-close';
            },

            toggleOptionsVisibility() {
                this.isOptionsVisible = !this.isOptionsVisible;
            },
        }));
    });
</script>
