<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\OrderCartItems;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $viewModelProvider */
/** @var OrderCartItems $viewModel */
$viewModel = $viewModelProvider(OrderCartItems::class);
?>
<?php // CART ITEMS ?>
<div id="cart-items-section" class="collapse collapse-arrow" x-data="OrderSummary" :class="cartItemsCollapseClass">
    <div
        class="px-0 text-xl font-normal border-b cursor-pointer collapse-title border-base-300"
        @click="toggleCartItemsVisibility"
    >
        <?php if ($viewModel->getCartItemsTotalQty() > 1): ?>
            <?= $eHtml($viewModel->getCartItemsTotalQty()) ?> <?= $eHtml(__('Items in Cart')) ?>
        <?php else: ?>
            1 <?= $eHtml(__('Item in Cart')) ?>
        <?php endif; ?>
    </div>
    <div class="py-4 collapse-content">
        <?php foreach ($viewModel->getCartItems() as $cartItem): ?>
        <div class="flex space-x-4" x-data="CartItem">
            <?php if ($cartItem->image): ?>
                <div class="w-20 h-20">
                    <img src="<?= $eHtmlAttr($cartItem->image->src) ?>"
                         width="<?= $eHtmlAttr($cartItem->image->width) ?>"
                         height="<?= $eHtmlAttr($cartItem->image->height) ?>"
                         alt="<?= $eHtmlAttr($cartItem->image->alt) ?>"
                         title="<?= $eHtmlAttr($cartItem->image->alt) ?>"
                         loading="lazy" class="h-auto max-w-full" />
                </div>
            <?php endif; ?>
            <div class="space-y-2 text-base font-normal">
                <h4><?= $eHtml($cartItem->name) ?></h4>
                <ul>
                    <li><span>Qty: </span><?= $eHtml($cartItem->qty) ?></li>
                    <li><?= /** @noEscape */ $cartItem->price ?></li>
                </ul>
                <?php if (!empty($cartItem->options)): ?>
                    <div class="collapse collapse-arrow" :class="optionsCollapseClass">
                        <div class="pl-1 -mt-4 collapse-title" @click="toggleOptionsVisibility">
                            <?= $eHtml(__('View Details')) ?>
                        </div>
                        <div class="pl-1 -mt-4 collapse-content">
                            <ul>
                                <?php foreach ($cartItem->options as $option): ?>
                                    <li>
                                        <span class="font-semibold">
                                            <?= $eHtml($option['label']) ?>: </span>
                                            <?= $eHtml($option['value']) ?>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
</div>
