<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var BillingAddress $viewModel */
$viewModel = $viewModelProvider(BillingAddress::class);
$isSameAsShipping = $viewModel->getBillingSameAsShippingValue();
?>
<div id="billing-address-details">
    <?= $block->getChildHtml('isBillingSame') ?>
    <div id="billing-address-form-wrapper" class="relative">
        <?php if (!$viewModel->isEditing() && $viewModel->isValidAddress()): ?>
            <div class="collapse collapse-open">
                <div class="collapse-content pt-4">
                    <div class="space-y-1 italic text-sm pl-6">
                        <?php foreach ($viewModel->getBillingAddressLines() as $addressLine): ?>
                            <p><?= $eHtml($addressLine) ?></p>
                        <?php endforeach; ?>
                    </div>
                    <?php if (!$isSameAsShipping): ?>
                        <div class="mt-4 px-4">
                            <button
                                type="button" class="btn btn-sm btn-neutral"
                                hx-target="#billing-address-section"
                                hx-indicator="#billing-address-section-loader"
                                hx-include="#is-billing-same"
                                hx-vals='{"show_form": <?= $eHtmlAttr((int)!$viewModel->isCustomerLoggedIn()) ?>}'
                                hx-get="<?= $block->getUrl('mahxcheckout/billing/editBilling') ?>"
                            >
                                <?= $eHtml(__('Edit')) ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
