<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\ViewModel\ShowBillingForm;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var string $nonce */
/** @var Esc $esc */
/** @var string $formKey */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(BillingAddress::class);
$showFormViewModel = $viewModelProvider->get(ShowBillingForm::class);
$isSameAsShipping = $viewModel->isBillingSameAsShipping();

if (!$showFormViewModel->canShowForm()) {
    return;
}
?>
<form id="billing-address-form" class="billing-address-form checkout-billing-address" x-data="BillingAddressForm">
    <?= $formKey ?>
    <fieldset id="billing-address-details" class="fieldset">
        <?php foreach ($viewModel->getAddressFields() as $field): ?>
            <?= $viewModel->renderField($field) ?>
        <?php endforeach; ?>
        <?= $block->getChildHtml('actions') ?>
    </fieldset>
    <?= $block->getChildHtml('luma_js') ?>
</form>
<?= $block->getChildHtml('loader') ?>
