<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\ViewModel\ShowBillingForm;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var Esc $esc */
/** @var string $formKey */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(BillingAddress::class);
$hxAttributesRenderer = $viewModelProvider->get(HxAttributesRenderer::class);
$showFormViewModel = $viewModelProvider->get(ShowBillingForm::class);
$isSameAsShipping = $viewModel->getBillingSameAsShippingValue();
?>
<div id="billing-address-details">
    <?= $block->getChildHtml('isBillingSame') ?>
    <div id="billing-address-form-wrapper" class="relative">
        <?php if (!$showFormViewModel->isEditing() && $viewModel->isValidAddress()): ?>
            <div class="address-lines collapse collapse-open">
                <div class="collapse-content pt-4">
                    <div class="space-y-1 italic text-sm pl-6">
                        <?php $addressLines = $viewModel->getBillingAddressLines() ?>
                        <p class="font-semibold"><?= $esc->html($addressLines->name) ?></p>
                        <p><?= $esc->html($addressLines->streetLine1 ?? '') ?></p>
                        <p><?= $esc->html($addressLines->streetLine2 ?? '') ?></p>
                        <p><?= $esc->html($addressLines->postcode ?? '') ?></p>
                        <p><?= $esc->html($addressLines->country ?? '') ?></p>
                        <p class="text-blue-600 mt-1"><?= $esc->html($addressLines->telephone ?? '') ?></p>
                    </div>
                    <?php if (!$isSameAsShipping): ?>
                        <div class="mt-4 px-4">
                            <button
                                type="button" class="btn btn-sm btn-neutral"
                                <?= $hxAttributesRenderer->hxBuilder()
                                    ->post('mahxcheckout/billing/editBilling')
                                    ->target('#billing-address-section')
                                    ->swapOuterHTML()
                                    ->include(['#is-billing-same', '[name=form_key]'])
                                    ->vals($showFormViewModel->editFormRequestParams())
                                    ->indicator('#billing-address-section-loader')
                                    ->render()
                                ?>
                            >
                                <?= $esc->html(__('Edit')) ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
