<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var BillingAddress $viewModel */

$viewModel = $viewModelProvider(BillingAddress::class);
$isSameAsShipping = $viewModel->isBillingSameAsShipping();
?>
<?php if ($viewModel->canShowForm()): ?>
    <form id="billing-address-form" x-data="BillingAddressForm">
        <?= $formKey ?>
        <div id="billing-address-details">
            <?php foreach ($viewModel->getAddressFields() as $field): ?>
                <?= $viewModel->renderField($field) ?>
            <?php endforeach; ?>
            <?= $block->getChildHtml('actions') ?>
        </div>
    </form>
    <?= $block->getChildHtml('loader') ?>
<?php endif; ?>
