<?php declare(strict_types=1);

use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\ViewModel\ShowBillingForm;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var BillingAddress $viewModel */
/** @var ShowBillingForm $showFormViewModel */
/** @var HxAttributesRenderer $hxAttributesRenderer */

$viewModel = $viewModelProvider(BillingAddress::class);
$hxAttributesRenderer = $viewModelProvider(HxAttributesRenderer::class);
$showFormViewModel = $viewModelProvider(ShowBillingForm::class);
$isSameAsShipping = $viewModel->getBillingSameAsShippingValue();
?>
<div id="billing-address-details">
    <?= $block->getChildHtml('isBillingSame') ?>
    <div id="billing-address-form-wrapper" class="relative">
        <?php if (!$showFormViewModel->isEditing() && $viewModel->isValidAddress()): ?>
            <div class="collapse collapse-open">
                <div class="collapse-content pt-4">
                    <div class="space-y-1 italic text-sm pl-6">
                        <?php foreach ($viewModel->getBillingAddressLines() as $addressLine): ?>
                            <p><?= $eHtml($addressLine) ?></p>
                        <?php endforeach; ?>
                    </div>
                    <?php if (!$isSameAsShipping): ?>
                        <div class="mt-4 px-4">
                            <button
                                type="button" class="btn btn-sm btn-neutral"
                                <?= $hxAttributesRenderer->hxBuilder()
                                    ->post('mahxcheckout/billing/editBilling')
                                    ->target('#billing-address-section')
                                    ->swapOuterHTML()
                                    ->include(['#is-billing-same', '[name=form_key]'])
                                    ->vals($showFormViewModel->editFormRequestParams())
                                    ->indicator('#billing-address-section-loader')
                                    ->render()
                                ?>
                            >
                                <?= $eHtml(__('Edit')) ?>
                            </button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
