<?php declare(strict_types=1);

use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\ViewModel\ShowBillingForm;
use MageHx\MahxCheckout\ViewModel\StepManager;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var BillingAddress $viewModel */
/** @var ShowBillingForm $showFormViewModel */
/** @var HxAttributesRenderer $hxAttributesRenderer */
/** @var StepManager $stepManager */

$stepManager = $viewModelProvider(StepManager::class);
$viewModel = $viewModelProvider(BillingAddress::class);
$showFormViewModel = $viewModelProvider(ShowBillingForm::class);
$hxAttributesRenderer = $viewModelProvider(HxAttributesRenderer::class);
$isSameAsShipping = $viewModel->getBillingSameAsShippingValue();
$vals = [
    'show_form' => (int)(!$viewModel->isCustomerLoggedIn() || !$showFormViewModel->currentCustomerHasAddress()),
    'show_cards' => (int)($viewModel->isCustomerLoggedIn() && $showFormViewModel->currentCustomerHasAddress()),
];
?>
<div class="form-control">
    <label class="label cursor-pointer justify-start space-x-2">
        <input
            id="is-billing-same" type="checkbox" name="is_billing_same" class="checkbox" value="1"
            <?= $isSameAsShipping ? 'checked' : '' ?>
            <?= $hxAttributesRenderer->hxBuilder()
                ->swapOuterHTML()
                ->indicator('#billing-address-section-loader')
                ->include('[name=form_key]')
                ->target('#billing-address-section')
                ->when($isSameAsShipping, fn ($hx) => $hx->post('mahxcheckout/billing/editBilling')->vals($vals))
                ->when(!$isSameAsShipping, fn ($hx) => $hx->post('mahxcheckout/billing/billingAddressPost'))
                ->render() ?>
        />
        <span class="label-text"><?= $eHtml(__('My billing and shipping address are the same')) ?></span>
    </label>
</div>
