<?php

use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\ViewModel\ShowBillingForm;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\BillingAddress;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var BillingAddress $viewModel */
/** @var ShowBillingForm $showFormViewModel */
/** @var HxAttributesRenderer $hxAttributesRenderer */

$viewModel = $viewModelProvider(BillingAddress::class);
$showFormViewModel = $viewModelProvider(ShowBillingForm::class);
$hxAttributesRenderer = $viewModelProvider(HxAttributesRenderer::class);
$isSameAsShipping = $viewModel->getBillingSameAsShippingValue();
?>
<div class="form-control">
    <label class="label cursor-pointer justify-start space-x-2">
        <input
            id="is-billing-same" type="checkbox" name="is_billing_same" class="checkbox" value="1"
            <?= $isSameAsShipping ? 'checked' : '' ?>
            hx-swap="outerHTML"
            hx-indicator="#billing-address-section-loader"
            hx-include="[name=form_key]"
            hx-target="<?= $eHtmlAttr($isSameAsShipping ? '#billing-address-section' : '#checkout-main-content') ?>"
            <?php if ($isSameAsShipping): ?>
                hx-post="<?= $eUrl($block->getUrl('mahxcheckout/billing/editBilling')) ?>"
                <?= $hxAttributesRenderer->vals($showFormViewModel->editFormRequestParams()) ?>
            <?php else: ?>
                hx-post="<?= $eUrl($block->getUrl('mahxcheckout/billing/billingAddressPost')) ?>"
            <?php endif; ?>
        />
        <span class="label-text"><?= $eHtml(__('My billing and shipping address are the same')) ?></span>
    </label>
</div>
