<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var string $nonce */
/** @var Esc $esc */
?>
<script nonce="<?= $esc->htmlAttr($nonce) ?>">
    'use strict';

    require(['jquery', 'MageHx_MahxCheckout/js/page-navigation'], ($, pageNavigation) => {
        $(() => {
            const billingAddressForm = document.getElementById('billing-address-form');
            const billingAddressFormManager = Object.assign(
                pageNavigation,
                BillingAddressForm(billingAddressForm)
            );
            billingAddressFormManager.init();
        });
    });
</script>
