<?php

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<!-- Main Content -->
<div id="checkout-main" class="max-w-7xl mx-auto px-4 py-8 bg-transparent" data-theme="light" x-data="PageNavigation">
    <?= $block->getChildHtml('checkout.notifications') ?>
    <?=  $block->getChildHtml('checkout.step.navigation') ?>
    <?=  $block->getChildHtml('checkout.main.content') ?>
</div>


