<?php
/** @var string $eHtmlAttr */
/** @var string $nonce */
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    const AppStorage = {
        orderSummary: {
            isCartItemsVisible: false,
            optionsVisibility: {},
        },
        shipping: {
            method: '',
        }
    };
    document.addEventListener('alpine:init', () => {
        Alpine.store('app', AppStorage);
    });
</script>
