<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;

/** @var Esc $esc */
/** @var string $nonce */
?>
<script nonce="<?= $esc->htmlAttr($nonce) ?>">
    const AppStorage = {
        orderSummary: {
            isCartItemsVisible: false,
            optionsVisibility: {},
        },
        shipping: {
            method: '',
        }
    };
    document.addEventListener('alpine:init', () => {
        Alpine.store('app', AppStorage);
    });
</script>
