<?php declare(strict_types=1);

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<div id="checkout"
     class="checkout-container max-w-7xl mx-auto px-4 py-8 bg-transparent"
     data-theme="light"
     x-data="PageNavigation"
>
    <?= $block->getChildHtml('checkout.notifications') ?>
    <?=  $block->getChildHtml('checkout.step.navigation') ?>
    <?=  $block->getChildHtml('checkout.main.content') ?>
</div>


