<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MahxCheckout\Block\Address\FieldRenderer;

/** @var FieldRenderer $block */
/** @var Esc $esc */

$fieldConfig = $block->getFieldConfig();

if (! $fieldConfig) {
    return;
}
?>
<div class="md:col-span-4">
    <input
        type="hidden"
        id="<?= $esc->htmlAttr($fieldConfig->getFieldId()) ?>"
        name="<?= $esc->htmlAttr($fieldConfig->name) ?>"
        value="<?= $esc->htmlAttr($fieldConfig->value)  ?>" />
</div>
