<?php

use MageHx\MahxCheckout\Block\Address\FieldRenderer;
use MageHx\MahxCheckout\Data\FormField\MultilineFieldMeta;

/** @var FieldRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */
/** @var MultilineFieldMeta $fieldMeta */

$fieldConfig = $block->getFieldConfig();

if (! $fieldConfig) {
    return;
}
$fieldMeta = $fieldConfig->meta;
$wrapperClasses = $block->getWrapperElemExtraClasses();
?>
<div
    class="<?= $classNames([
        'field form-control w-full max-w-lg',
        '_required' => $fieldConfig->required,
        $wrapperClasses => $wrapperClasses
    ]) ?>"
    <?= $block->getWrapperAdditionalAttributes() ?>
>
    <?= /** @noEscape */ $block->getBeforeInputHtml() ?>
    <label class="label" for="<?= $eHtmlAttr($fieldConfig->getFieldId() . '-0') ?>">
        <span class="label-text">
            <?= $eHtml($fieldConfig->label) ?>
            <?php if ($fieldConfig->required): ?>
                <span class="text-red-500 ml-1" aria-hidden="true">*</span>
            <?php endif; ?>
        </span>
    </label>
    <div class="control space-y-2">
        <?php foreach (range(0, ($fieldMeta->lineCount) - 1) as $index): ?>
            <div class="<?= $classNames([
                    'field', '_required' => $fieldConfig->required, 'additional' => $index > 0
                ]) ?>"
            >
                <input
                    type="text"
                    class="input-text input input-bordered input-sm md:input-md w-full max-w-lg"
                    id="<?= $eHtmlAttr($fieldConfig->getFieldId() . '-' . $index) ?>"
                    name="<?= $eHtmlAttr($fieldConfig->name) ?>[<?= $eHtmlAttr($index) ?>]"
                    value="<?= $eHtmlAttr($fieldConfig->value[$index] ?? '')  ?>"
                    <?= /** @noEscape */ !$index ? $block->getInputAdditionalAttributes() : '' ?>
                />
            </div>
        <?php endforeach; ?>
    </div>
    <?= /** @noEscape */ $block->getAfterInputHtml() ?>
</div>
