<?php

use MageHx\MahxCheckout\Block\Address\FieldRenderer;

/** @var FieldRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */

$fieldAttributes = $block->getFieldAttributes();

if (! $fieldAttributes) {
    return;
}
$wrapperClasses = $block->getWrapperElemExtraClasses();
?>
<div
    class="<?= $classNames(['form-control w-full max-w-sm', $wrapperClasses => $wrapperClasses]) ?>"
    <?= $block->getWrapperAdditionalAttributes() ?>
>
    <?= /** @noEscape */ $block->getBeforeInputHtml() ?>
    <label class="label" for="<?= $eHtmlAttr($fieldAttributes->getFieldId() . '-0') ?>">
        <span class="label-text">
            <?= $eHtml($fieldAttributes->label) ?>
            <?php if ($fieldAttributes->required): ?>
                <span class="text-red-500 ml-1" aria-hidden="true">*</span>
            <?php endif; ?>
        </span>
    </label>
    <div class="space-y-2">
        <?php foreach (range(0, $fieldAttributes->additionalData['multilineCount'] ?? 0) as $index): ?>
            <?php if ($index === 0): ?><div><?php endif; ?>
            <input
                type="text"
                class="input input-bordered w-full max-w-sm"
                id="<?= $eHtmlAttr($fieldAttributes->getFieldId() . '-' . $index) ?>"
                name="<?= $eHtmlAttr($fieldAttributes->name) ?>[<?= $eHtmlAttr($index) ?>]"
                value="<?= $eHtmlAttr($fieldAttributes->value[$index] ?? '')  ?>"
                <?= /** @noEscape */ !$index ? $block->getInputAdditionalAttributes() : '' ?>
            />
            <?php if ($index === 0): ?></div><?php endif; ?>
        <?php endforeach; ?>
    </div>
    <?= /** @noEscape */ $block->getAfterInputHtml() ?>
</div>
