<?php

use MageHx\MahxCheckout\Block\Address\FieldRenderer;
use MageHx\MahxCheckout\Enum\AdditionalFieldAttribute as AFA;

/** @var FieldRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */

$fieldAttributes = $block->getFieldAttributes();

if (! $fieldAttributes) {
    return;
}

$wrapperClasses = $block->getWrapperElemExtraClasses();
?>
<div
    class="<?= $classNames(['form-control w-full max-w-sm', $wrapperClasses => $wrapperClasses]) ?>"
    <?= $block->getWrapperAdditionalAttributes() ?>
>
    <?= /** @noEscape */ $block->getBeforeInputHtml() ?>
    <label class="label" for="<?= $eHtmlAttr($fieldAttributes->getFieldId()) ?>">
        <span class="label-text">
            <?= $eHtml($fieldAttributes->label) ?>
            <?php if ($fieldAttributes->required): ?>
                <span class="text-red-500 ml-1" aria-hidden="true">*</span>
            <?php endif; ?>
        </span>
    </label>
    <select
        class="select select-bordered select-sm"
        id="<?= $eHtmlAttr($fieldAttributes->getFieldId()) ?>"
        name="<?= $eHtmlAttr($fieldAttributes->name) ?>"
        <?= /** @noEscape */ $block->getInputAdditionalAttributes() ?>
    >
        <option value=""><?= $eHtml($fieldAttributes->additionalData[AFA::DEFAULT_OPTION_LABEL->value] ?? '') ?></option>
        <?php foreach ($fieldAttributes->additionalData[AFA::OPTIONS->value] ?? [] as $value => $label): ?>
            <option value="<?= $eHtmlAttr($value) ?>" <?= $fieldAttributes->value == $value ? 'selected' : '' ?>>
                <?= $eHtml($label) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?= /** @noEscape */ $block->getAfterInputHtml() ?>
</div>
