<?php

use MageHx\MahxCheckout\Block\Address\FieldRenderer;
use MageHx\MahxCheckout\Data\FormField\SelectFieldMeta;
use MageHx\MahxCheckout\Enum\AdditionalFieldAttribute as AFA;

/** @var FieldRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */
/** @var SelectFieldMeta $fieldMeta */

$fieldConfig = $block->getFieldConfig();

if (! $fieldConfig) {
    return;
}

$fieldMeta = $fieldConfig->meta;
$wrapperClasses = $block->getWrapperElemExtraClasses();
?>
<div
    class="<?= $classNames([
        'field form-control w-full max-w-lg',
        '_required' => $fieldConfig->required,
        $wrapperClasses => $wrapperClasses
    ]) ?>"
    <?= $block->getWrapperAdditionalAttributes() ?>
>
    <?= /** @noEscape */ $block->getBeforeInputHtml() ?>
    <label class="label" for="<?= $eHtmlAttr($fieldConfig->getFieldId()) ?>">
        <span class="label-text">
            <?= $eHtml($fieldConfig->label) ?>
            <?php if ($fieldConfig->required): ?>
                <span class="text-red-500 ml-1" aria-hidden="true">*</span>
            <?php endif; ?>
        </span>
    </label>
    <div class="control">
        <select
            class="select select-bordered select-sm w-full md:select-md"
            id="<?= $eHtmlAttr($fieldConfig->getFieldId()) ?>"
            name="<?= $eHtmlAttr($fieldConfig->name) ?>"
            <?= /** @noEscape */ $block->getInputAdditionalAttributes() ?>
        >
            <option value=""><?= $eHtml($fieldMeta->defaultOptionLabel) ?></option>
            <?php foreach ($fieldMeta->options as $value => $label): ?>
                <option value="<?= $eHtmlAttr($value) ?>" <?= $fieldConfig->value == $value ? 'selected' : '' ?>>
                    <?= $eHtml($label) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <?= /** @noEscape */ $block->getAfterInputHtml() ?>
</div>
