<?php

use MageHx\MahxCheckout\Block\Address\FieldRenderer;

/** @var FieldRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */

$fieldConfig = $block->getFieldConfig();

if (! $fieldConfig) {
    return;
}
$wrapperClasses = $block->getWrapperElemExtraClasses();
?>
<div
    class="<?= $classNames([
        'field form-control w-full max-w-lg',
        '_required' => $fieldConfig->required,
        $wrapperClasses => $wrapperClasses
    ]) ?>"
    <?= $block->getWrapperAdditionalAttributes() ?>
>
    <?= /** @noEscape */ $block->getBeforeInputHtml() ?>
    <label class="label" for="<?= $eHtmlAttr($fieldConfig->getFieldId()) ?>">
        <span class="<?= $classNames([
                'label-text',
                "after:content-['*'] after:text-red-500 after:ml-1" => $fieldConfig->required
            ]) ?>">
            <?= $eHtml($fieldConfig->label) ?>
        </span>
    </label>
   <div class="control">
       <input
           type="text"
           id="<?= $eHtmlAttr($fieldConfig->getFieldId()) ?>"
           name="<?= $eHtmlAttr($fieldConfig->name) ?>"
           class="input-text input input-bordered input-sm md:input-md w-full max-w-lg"
           value="<?= $eHtmlAttr($fieldConfig->value)  ?>"
           <?= /** @noEscape */ $block->getInputAdditionalAttributes() ?>
       />
   </div>
    <?= /** @noEscape */ $block->getAfterInputHtml() ?>
</div>
