<?php

use MageHx\MahxCheckout\Block\Address\FieldRenderer;

/** @var FieldRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */

$fieldConfig = $block->getFieldConfig();

if (! $fieldConfig) {
    return;
}
$wrapperClasses = $block->getWrapperElemExtraClasses();
?>
<div
    class="<?= $classNames(['form-control w-full max-w-lg', $wrapperClasses => $wrapperClasses]) ?>"
    <?= $block->getWrapperAdditionalAttributes() ?>
>
    <?= /** @noEscape */ $block->getBeforeInputHtml() ?>
    <label class="label" for="<?= $eHtmlAttr($fieldConfig->getFieldId()) ?>">
        <span class="label-text">
            <?= $eHtml($fieldConfig->label) ?>
            <?php if ($fieldConfig->required): ?>
                <span class="text-red-500 ml-1" aria-hidden="true">*</span>
            <?php endif; ?>
        </span>
    </label>
    <input
        type="text"
        id="<?= $eHtmlAttr($fieldConfig->getFieldId()) ?>"
        name="<?= $eHtmlAttr($fieldConfig->name) ?>"
        class="input input-bordered input-sm md:input-md w-full max-w-lg"
        value="<?= $eHtmlAttr($fieldConfig->value)  ?>"
        <?= /** @noEscape */ $block->getInputAdditionalAttributes() ?>
    />
    <?= /** @noEscape */ $block->getAfterInputHtml() ?>
</div>
