<?php

use MageHx\MahxCheckout\Block\Address\FieldRenderer;

/** @var FieldRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */

$fieldAttributes = $block->getFieldAttributes();

if (! $fieldAttributes) {
    return;
}
$wrapperClasses = $block->getWrapperElemExtraClasses();
?>
<div
    class="<?= $classNames(['form-control w-full max-w-sm', $wrapperClasses => $wrapperClasses]) ?>"
    <?= $block->getWrapperAdditionalAttributes() ?>
>
    <?= /** @noEscape */ $block->getBeforeInputHtml() ?>
    <label class="label" for="<?= $eHtmlAttr($fieldAttributes->getFieldId()) ?>">
        <span class="label-text">
            <?= $eHtml($fieldAttributes->label) ?>
            <?php if ($fieldAttributes->required): ?>
                <span class="text-red-500 ml-1" aria-hidden="true">*</span>
            <?php endif; ?>
        </span>
    </label>
    <input
        type="text"
        id="<?= $eHtmlAttr($fieldAttributes->getFieldId()) ?>"
        name="<?= $eHtmlAttr($fieldAttributes->name) ?>"
        class="input input-bordered input-sm w-full max-w-sm"
        value="<?= $eHtmlAttr($fieldAttributes->value)  ?>"
        <?= /** @noEscape */ $block->getInputAdditionalAttributes() ?>
    />
    <?= /** @noEscape */ $block->getAfterInputHtml() ?>
</div>
