<?php declare(strict_types=1);
/** @var string $eHtmlAttr */
/** @var string $nonce */
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    'use strict';

    define('MageHx_MahxCheckout/js/page-navigation', [], function () {
        const pageNavigation = PageNavigation();
        pageNavigation.$store = {
            checkoutStepStorage: CheckoutStepStorage
        };
        pageNavigation.init();

        return pageNavigation;
    })
</script>

