<?php declare(strict_types=1);

use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingMethods;

/** @var Template $block */
/** @var string $nonce */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var ShippingMethods $viewModel */
/** @var DesignThemeInfo $themeInfo */

$themeInfo = $viewModelProvider(DesignThemeInfo::class);
$viewModel = $viewModelProvider(ShippingMethods::class);
$isHtmxOob = (bool)$block->getData('is_htmx_oob');
?>
<div
    id="shipping-methods-section"
    class="mt-12 relative"
    <?= $eHtml($isHtmxOob ? 'hx-swap-oob="true"' : '') ?>
>
    <?= $block->getChildHtml('formTitle') ?>
    <div class="overflow-x-auto">
        <form id="shipping-methods-form" class="form methods-shipping" x-data="ShippingMethodsForm">
            <table class="table-checkout-shipping-method table md:max-w-lg">
                <tbody>
                <?php foreach ($block->getShippingMethods() as $method): ?>
                    <?php
                        $methodValue = $viewModel->getInputValueFromMethod($method);
                        $id = "shipping-method-{$methodValue}";
                    ?>
                    <tr class="row">
                        <td class="col col-method w-12">
                            <input
                                id="<?= $eHtmlAttr($id) ?>" type="radio" class="radio" name="shipping_method"
                                value="<?= $eHtmlAttr($methodValue) ?>"
                                <?= $methodValue === $viewModel->getSelectedMethod() ? 'checked': '' ?>/>
                        </td>
                        <td class="col col-price font-bold">
                            <label for="<?= $eHtmlAttr($id) ?>" class="price cursor-pointer">
                                <span class="price"><?= /** @noEscape */ $viewModel->getMethodPriceHtml($method) ?></span>
                            </label>
                        </td>
                        <td class="col col-method">
                            <label for="<?= $eHtmlAttr($id) ?>" class="cursor-pointer">
                                <?= $eHtml($method->getMethodTitle()) ?>
                            </label>
                        </td>
                        <td class="col col-method">
                            <label for="<?= $eHtmlAttr($id) ?>" class="cursor-pointer">
                                <?= $eHtml($method->getCarrierTitle()) ?>
                            </label>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </form>
    </div>
    <?= $block->getChildHtml('loader') ?>
    <?php if ($themeInfo->isMagentoTheme()): ?>
        <script nonce="<?= $eHtmlAttr($nonce) ?>">
            'use strict';

            require(['jquery', 'MageHx_MahxCheckout/js/page-navigation'], ($, pageNavigation) => {
                $(() => {
                    const shippingMethodsForm = document.getElementById('shipping-methods-form');
                    if (shippingMethodsForm) {
                        const shippingMethodsFormManager = Object.assign(
                            pageNavigation,
                            ShippingMethodsForm(shippingMethodsForm)
                        );
                        shippingMethodsFormManager.init();
                    }
                });
            });
        </script>
    <?php endif; ?>
</div>
