<?php declare(strict_types=1);

use MageHx\HtmxActions\ViewModel\HxAttributesRenderer;
use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingMethods;

/** @var Template $block */
/** @var string $nonce */
/** @var Esc $esc */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(ShippingMethods::class);
$hxAttrRenderer = $viewModelProvider->get(HxAttributesRenderer::class);
?>
<div
    id="shipping-methods-section"
    class="mt-12 relative"
    <?= $hxAttrRenderer->renderHxSwapOOB($block) ?>
>
    <?= $block->getChildHtml('formTitle') ?>
    <div class="overflow-x-auto">
        <form id="shipping-methods-form" class="form methods-shipping" x-data="ShippingMethodsForm">
            <table class="table-checkout-shipping-method table md:max-w-lg">
                <tbody>
                <?php foreach ($block->getShippingMethods() as $method): ?>
                    <?php
                        $methodValue = $viewModel->getInputValueFromMethod($method);
                        $id = "shipping-method-{$methodValue}";
                    ?>
                    <tr class="row">
                        <td class="col col-method w-12">
                            <input
                                id="<?= $esc->htmlAttr($id) ?>" type="radio" class="radio" name="shipping_method"
                                value="<?= $esc->htmlAttr($methodValue) ?>"
                                <?= $methodValue === $viewModel->getSelectedMethod() ? 'checked': '' ?>/>
                        </td>
                        <td class="col col-price font-bold">
                            <label for="<?= $esc->htmlAttr($id) ?>" class="price cursor-pointer">
                                <span class="price"><?= /** @noEscape */ $viewModel->getMethodPriceHtml($method) ?></span>
                            </label>
                        </td>
                        <td class="col col-method">
                            <label for="<?= $esc->htmlAttr($id) ?>" class="cursor-pointer">
                                <?= $esc->html($method->getMethodTitle()) ?>
                            </label>
                        </td>
                        <td class="col col-method">
                            <label for="<?= $esc->htmlAttr($id) ?>" class="cursor-pointer">
                                <?= $esc->html($method->getCarrierTitle()) ?>
                            </label>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </form>
    </div>
    <?= $block->getChildHtml('loader') ?>
    <?= $block->getChildHtml('luma_js') ?>
</div>
