<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingMethods;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var ShippingMethods $viewModel */
$viewModel = $viewModelProvider(ShippingMethods::class);
$isHtmxOob = (bool)$block->getData('is_htmx_oob');
?>
<div
    id="shipping-methods-section"
    class="mt-12 relative"
    <?= $eHtml($isHtmxOob ? 'hx-swap-oob="true"' : '') ?>
>
    <?= $block->getChildHtml('formTitle') ?>
    <div class="overflow-x-auto">
        <form id="shipping-methods-form" x-data="ShippingMethodsForm">
            <table class="table md:max-w-lg">
                <tbody>
                <?php foreach ($block->getShippingMethods() as $method): ?>
                    <?php
                        $methodValue = $viewModel->getInputValueFromMethod($method);
                        $id = "shipping-method-{$methodValue}";
                    ?>
                    <tr>
                        <th class="w-12">
                            <input
                                id="<?= $eHtmlAttr($id) ?>" type="radio" class="radio" name="shipping_method"
                                value="<?= $eHtmlAttr($methodValue) ?>"
                                <?= $methodValue === $viewModel->getSelectedMethod() ? 'checked': '' ?>/>
                        </th>
                        <td class="font-bold">
                            <label for="<?= $eHtmlAttr($id) ?>" class="cursor-pointer">
                                <?= /** @noEscape */ $viewModel->getMethodPriceHtml($method) ?>
                            </label>
                        </td>
                        <td>
                            <label for="<?= $eHtmlAttr($id) ?>" class="cursor-pointer">
                                <?= $eHtml($method->getMethodTitle()) ?>
                            </label>
                        </td>
                        <td>
                            <label for="<?= $eHtmlAttr($id) ?>" class="cursor-pointer">
                                <?= $eHtml($method->getCarrierTitle()) ?>
                            </label>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </form>
    </div>
    <div
        id="shipping-loader"
        class="htmx-indicator checkout-loader est-shipping-loader est-shipping-country-loader"
    >
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
