<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\Block\PaymentRenderer;
use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;

/** @var PaymentRenderer $block */
/** @var Esc $esc */
/** @var ViewModelProvider $viewModelProvider */
/** @var HxAttributesRenderer $hxAttrRenderer */

$payment = $block->getPaymentData();
$hxAttrRenderer = $viewModelProvider->get(HxAttributesRenderer::class);
?>
<div class="payment-method form-control w-max">
    <div class="payment-method-title flex items-center gap-x-1">
        <input
            type="radio" class="radio checked:bg-neutral" name="payment_method"
            value="<?= $esc->htmlAttr($payment->code) ?>"
            id="payment_method_<?= $esc->htmlAttr($payment->code) ?>"
            <?= $block->isSelected() ? 'checked="checked"': '' ?>
            <?= $hxAttrRenderer->hxBuilder()
                ->post('mahxcheckout/form/paymentMethodPost')
                ->target('#payment-methods-section')
                ->indicator('.save-payment-loader')
                ->swapOuterHTML()
                ->render()
            ?>
        />
        <label for="payment_method_<?= $esc->htmlAttr($payment->code) ?>" class="label cursor-pointer justify-start space-x-2">
            <span class="label-text"><?= $esc->html($payment->title) ?></span>
        </label>
    </div>
</div>
