<?php

use MageHx\MahxCheckout\Block\PaymentRenderer;

/** @var PaymentRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */

$payment = $block->getPaymentData();
?>
<div class="form-control">
    <label class="label cursor-pointer justify-start space-x-2">
        <input
            type="radio" class="radio checked:bg-neutral" name="payment_method"
            value="<?= $eHtmlAttr($payment->code) ?>"
            id="payment_form_method__<?= $eHtmlAttr($payment->code) ?>"
            <?= $block->isSelected() ? 'checked="checked"': '' ?>
            hx-indicator="#checkout-page-loader"
            hx-target="#checkout-main-content"
            hx-swap="outerHTML"
            hx-post="<?= $eUrl($block->getUrl('mahxcheckout/form/paymentMethodPost')) ?>"
            hx-on:afterSwap="dispatchPaymentSaved"
        />
        <span class="label-text"><?= $eHtml($payment->title) ?></span>
    </label>
</div>
