<?php

use MageHx\HtmxActions\Enums\HtmxCoreAttributes;
use MageHx\MahxCheckout\Block\PaymentRenderer;
use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;

/** @var PaymentRenderer $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var HxAttributesRenderer $hxAttrRenderer */

$payment = $block->getPaymentData();
$hxAttrRenderer = $viewModelProvider(HxAttributesRenderer::class);
?>
<div class="payment-method form-control w-max">
    <div class="payment-method-title flex items-center gap-x-1">
        <input
            type="radio" class="radio checked:bg-neutral" name="payment_method"
            value="<?= $eHtmlAttr($payment->code) ?>"
            id="payment_method_<?= $eHtmlAttr($payment->code) ?>"
            <?= $block->isSelected() ? 'checked="checked"': '' ?>
            <?= $hxAttrRenderer->hxBuilder()
                ->post('mahxcheckout/form/paymentMethodPost')
                ->target('#payment-methods-section')
                ->indicator('.save-payment-loader')
                ->swapOuterHTML()
                ->render()
            ?>
        />
        <label for="payment_method_<?= $eHtmlAttr($payment->code) ?>" class="label cursor-pointer justify-start space-x-2">
            <span class="label-text"><?= $eHtml($payment->title) ?></span>
        </label>
    </div>
</div>
