<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var string $nonce */
/** @var Esc $esc */
?>
<script nonce="<?= $esc->htmlAttr($nonce) ?>">
    'use strict';

    require(['jquery', 'MageHx_MahxCheckout/js/page-navigation'], ($, pageNavigation) => {
        $(() => {
            const shippingMethodsForm = document.getElementById('shipping-methods-form');
            if (shippingMethodsForm) {
                const shippingMethodsFormManager = Object.assign(
                    pageNavigation,
                    ShippingMethodsForm(shippingMethodsForm)
                );
                shippingMethodsFormManager.init();
            }
        });
    });
</script>
