<?php
/** @var string $eHtmlAttr */
/** @var string $nonce */
/** @var Closure $eJs */
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        Alpine.data('PaymentMethodsForm', () => ({
            form: null,
            validator: null,

            init() {
                this.form = this.$el;
                this.validator = mahxCheckout.validator(this.form);
                this.validator.addRequiredGroup(this.form, '<?= $eJs(__("The payment method is missing. Select the payment method and try again.")) ?>');
                this.addValidatorToPageNavigation(this.form.id, this.validator);
            },

            dispatchPaymentSaved(event) {
                this.$dispatch('mahxcheckout-payment-saved', { htmxEvent: event });
            },
        }));
    });
</script>
