<?php

use MageHx\MahxCheckout\Block\PaymentMethods;

/** @var PaymentMethods $block */
/** @var Closure $eHtmlAttr */
/** @var string $formKey */
/** @var Closure $classNames */
?>
<div id="payment-methods-section" class="<?= $classNames(['relative', 'mt-12' => $block->isVirtualCart()]) ?>">
    <?= $block->getChildHtml('formTitle') ?>
    <div class="overflow-x-auto">
        <form
            id="payment-methods-form"
            x-data="PaymentMethodsForm"
            data-validation="<?= $eHtmlAttr($block->getValidationJson()) ?>"
        >
            <?= $formKey ?>
            <?php foreach ($block->getPaymentMethods() as $method): ?>
                <?= $block->getPaymentHtml($method) ?>
            <?php endforeach; ?>
        </form>
    </div>
    <div id="payment-loader" class="htmx-indicator checkout-loader save-payment-loader">
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>
