<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\PaymentMethods;

/** @var Template $block */
/** @var Closure $eHtmlAttr */
/** @var string $formKey */
/** @var Closure $classNames */
/** @var Closure $viewModelProvider */
/** @var PaymentMethods $viewModel */

$viewModel = $viewModelProvider(PaymentMethods::class);
?>
<div id="payment-methods-section" class="<?= $classNames(['relative', 'mt-12' => $viewModel->isVirtualCart()]) ?>">
    <?= $block->getChildHtml('formTitle') ?>
    <div class="overflow-x-auto">
        <form
            id="payment-methods-form"
            x-data="PaymentMethodsForm"
            data-validation="<?= $eHtmlAttr($viewModel->getValidationDataJson()) ?>"
        >
            <?= $formKey ?>
            <?php foreach ($viewModel->getPaymentMethods() as $method): ?>
                <?= $viewModel->renderPayment($method) ?>
            <?php endforeach; ?>
        </form>
    </div>
    <div id="payment-loader"
         class="htmx-indicator absolute inset-0 flex items-center justify-center bg-white/50 pointer-events-none">
        <span class="loading loading-dots loading-md"></span>
        <span class="loading loading-dots loading-md"></span>
        <span class="loading loading-dots loading-md"></span>
    </div>
</div>
