<?php declare(strict_types=1);

use MageHx\HtmxActions\Model\HxAttributeRender\HxAttributeBuilder;
use MageHx\HtmxActions\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\StepManager;

/** @var Template $block */
/** @var string $nonce */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var StepManager $viewModel */
/** @var HxAttributesRenderer $hxRenderer */
/** @var DesignThemeInfo $themeInfo */

$themeInfo = $viewModelProvider(DesignThemeInfo::class);
$viewModel = $viewModelProvider(StepManager::class);
$hxRenderer = $viewModelProvider(HxAttributesRenderer::class);
$currentStep = $viewModel->getCurrentStep();
?>
<div id="page-actions" class="h-24 w-full mt-12" x-data="PageAction" <?= $hxRenderer->renderHxSwapOOB($block) ?>>
    <div class="actions flex items-center justify-center">
        <button
            id="step-navigation-button"
            type="button"
            class="btn btn-primary btn-lg"
            data-role="opc-continue"
            <?= $hxRenderer->hxBuilder()
                ->post($currentStep->saveDataUrl)
                ->include($viewModel->getHtmxIncludesForCurrentStep())
                ->indicator('#checkout-page-loader')
                ->when($viewModel->isOnLastStep(), fn (HxAttributeBuilder $hx) => $hx->swapNone())
                ->when(!$viewModel->isOnLastStep(), fn (HxAttributeBuilder $hx) =>
                    $hx->target('#checkout-main-content')->swapOuterHTML()
                )->render()
            ?>
        >
            <?= $eHtml($viewModel->getCurrentStep()->buttonLabel) ?>
        </button>
    </div>
    <?php if ($themeInfo->isMagentoTheme()): ?>
        <script nonce="<?= $eHtmlAttr($nonce) ?>">
            'use strict';

            require(['jquery', 'MageHx_MahxCheckout/js/page-navigation'], ($, pageNavigation) => {
                $(() => {
                    const pageActions = document.getElementById('page-actions');
                    const pageActionsManager = Object.assign(pageNavigation, PageAction(pageActions));
                    pageActionsManager.init();
                });
            });
        </script>
    <?php endif; ?>
</div>
