<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\StepManager;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var StepManager $viewModel */
$viewModel = $viewModelProvider(StepManager::class);
?>
<input type="hidden" name="step" id="current-step" :value="currentStep.name" />

<div
    id="auto-step-content-loader"
    hx-post="<?= $eUrl($block->getUrl('mahxcheckout/step/getStepContent')) ?>"
    hx-include="#current-step,[name=form_key]"
    hx-trigger="load"
    hx-target="#checkout-main-content"
    hx-swap="outerHTML"
    hx-indicator="#step-loader"
>
</div>

<div id="step-navigation-section" class="w-full py-4 mb-4">
    <div class="px-4 mx-auto max-w-7xl">
        <ul class="text-base steps">
            <?php foreach ($viewModel->getStepsInfo() as $step): ?>
                <li class="step !min-w-56 cursor-pointer"
                    data-step-name="<?= $eHtmlAttr($step->name) ?>"
                    x-data="NavItem"
                    :class="stepExtraClass"
                    :data-content="stepDataContent"
                    hx-trigger="click"
                    hx-target="#checkout-main-content"
                    hx-swap="outerHTML"
                    hx-include="[name=form_key]"
                    hx-indicator="#checkout-page-loader"
                    hx-post="<?= $eUrl($block->getUrl('mahxcheckout/step/getStepContent', ['step' => $step->name])) ?>"
                >
                    <?= $eHtml($step->label) ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
