<?php declare(strict_types=1);

use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\StepManager;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $classNames */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var StepManager $viewModel */
/** @var HxAttributesRenderer $hxRenderer */

$viewModel = $viewModelProvider(StepManager::class);
$hxRenderer = $viewModelProvider(HxAttributesRenderer::class);
?>
<div id="step-navigation-section" class="w-full py-4 mb-4" <?= $hxRenderer->renderHxSwapOOB($block) ?>>
    <input type="hidden" name="step" id="current-step" :value="currentStep.name" />
    <div class="px-4 mx-auto max-w-7xl">
        <ul class="opc-progress-bar text-base steps">
            <?php foreach ($viewModel->getStepsInfo() as $step): ?>
                <li class="<?= $classNames([
                        'opc-progress-bar-item step !min-w-56 cursor-pointer',
                        '_active step-success font-extrabold' => $viewModel->isStepCompleted($step)
                    ]) ?>"
                    data-step-name="<?= $eHtmlAttr($step->name) ?>"
                    hx-trigger="click"
                    hx-target="#checkout-main-content"
                    hx-swap="outerHTML"
                    hx-include="[name=form_key]"
                    hx-indicator="#checkout-page-loader"
                    hx-post="<?= $eUrl($block->getUrl('mahxcheckout/step/getStepContent', ['step' => $step->name])) ?>"
                >
                    <span><?= $eHtml($step->label) ?></span>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
