<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;

/** @var Esc $esc */
/** @var string $nonce */
?>
<script nonce="<?= $esc->htmlAttr($nonce) ?>">
    'use strict';

    function CheckoutNotification(elem) {
        let timer;

        return {
            root: null,
            show: false,

            init() {
                this.root = elem || this.$el;
                clearTimeout(timer);
                this.toggleNotifications();
                timer = setTimeout(this.toggleNotifications.bind(this),  3000);
            },

            toggleNotifications() {
                this.show = !this.show;
                const alertElems = htmx.findAll(this.root, '.alert');
                Array.from(alertElems).forEach((alertItem) => {
                    htmx.toggleClass(alertItem, 'show');
                });
            },
        };
    }
    document.addEventListener('alpine:init', () => {
        Alpine.data('Notification', CheckoutNotification);
    });
</script>
