<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;

/** @var Esc $esc */
/** @var string $nonce */
?>
<script nonce="<?= $esc->htmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        let timer;
        Alpine.data('Notification', () => ({
            show: true,

            init() {
                clearTimeout(timer);
                timer = setTimeout(() => this.setShow(false),  3000);
            },

            setShow(status) {
                this.show = status;
            },
        }));
    });
</script>
