<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MahxCheckout\Block\Notifications;

/** @var Esc $esc */
/** @var Notifications $block */
?>
<div id="notifications-container" <?= $block->isHtmxOOBNeeded() ?  'hx-swap-oob="true"' : ''?>>
    <?php if (!empty($block->getValidationErrors())): ?>
        <div class="toast toast-top toast-end z-50" data-role="notification" x-data="Notification">
            <?php foreach ($block->getValidationErrors() as $message): ?>
                <div class="alert alert-error" x-show="show">
                    <span><?= $esc->html(__($message)) ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (!empty($block->getGenericErrorMessage())): ?>
    <div class="toast toast-top toast-end z-50" data-role="notification" x-data="Notification">
        <div class="alert alert-warning" x-show="show">
            <span><?= $esc->html($block->getGenericErrorMessage()) ?></span>
        </div>
    </div>
    <?php endif; ?>

    <?php if (!empty($block->getSuccessMessage())): ?>
        <div class="toast toast-top toast-end z-50" data-role="notification" x-data="Notification">
            <div class="alert alert-success" x-show="show">
                <span><?= $esc->html($block->getSuccessMessage()) ?></span>
            </div>
        </div>
    <?php endif; ?>
    <?= $block->getChildHtml('luma_js') ?>
</div>
