<?php

use MageHx\MahxCheckout\Block\Notifications;

/** @var Closure $eHtml */
/** @var Notifications $block */
?>
<div id="notifications-container" <?= $block->isHtmxOOBNeeded() ?  'hx-swap-oob="true"' : ''?>>
    <?php if (!empty($block->getValidationErrors())): ?>
        <div class="toast toast-top toast-end" x-data="Notification" x-show="show">
            <?php foreach ($block->getValidationErrors() as $message): ?>
                <div class="alert alert-error">
                    <span><?= $eHtml(__($message)) ?></span>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (!empty($block->getGenericErrorMessage())): ?>
    <div class="toast toast-top toast-end" x-data="Notification" x-show="show">
        <div class="alert alert-warning">
            <span><?= $eHtml($block->getGenericErrorMessage()) ?></span>
        </div>
    </div>
    <?php endif; ?>

    <?php if (!empty($block->getSuccessMessage())): ?>
        <div class="toast toast-top toast-end" x-data="Notification" x-show="show">
            <div class="alert alert-success">
                <span><?= $eHtml($block->getSuccessMessage()) ?></span>
            </div>
        </div>
    <?php endif; ?>
</div>
