<?php

use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Closure $eHtmlAttr */
/** @var Closure $classNames */
$id = $block->getData('id') ?? '';
$extraClass = $block->getData('extra_class') ?? '';
?>
<div
    id="<?= $eHtmlAttr($id) ?>"
    class="<?= $classNames([
        'htmx-indicator section-loader absolute inset-0 flex items-center justify-center bg-white/50 pointer-events-none',
        $extraClass => $extraClass,
    ]) ?>"
>
    <span class="loading loading-dots loading-md"></span>
    <span class="loading loading-dots loading-md"></span>
    <span class="loading loading-dots loading-md"></span>
</div>
