<div id="step-loader" class="w-full">
    <div class="flex flex-col gap-4">
        <div class="skeleton h-4 w-28"></div>
        <div class="skeleton h-4 w-full"></div>
        <div class="skeleton h-4 w-full"></div>
        <div class="skeleton h-32 w-full"></div>
    </div>

    <div class="flex flex-col gap-4 mt-12">
        <div class="skeleton h-4 w-28"></div>
        <div class="skeleton h-4 w-full"></div>
        <div class="skeleton h-4 w-full"></div>
        <div class="skeleton h-32 w-full"></div>
    </div>

    <div class="flex flex-col gap-4 mt-12">
        <div class="skeleton h-4 w-28"></div>
        <div class="skeleton h-4 w-full"></div>
        <div class="skeleton h-4 w-full"></div>
        <div class="skeleton h-32 w-full"></div>
    </div>
</div>
