<?php

use MageHx\MahxCheckout\ViewModel\BillingAddressFormActions;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var BillingAddressFormActions $viewModel */

$viewModel = $viewModelProvider(BillingAddressFormActions::class);
?>
<?php if ($viewModel->canShow()): ?>
<div class="flex items-center justify-end space-x-4">
    <button
        class="btn btn-ghost" type="button"
        @click="handleBillingCancel"
        hx-target="#billing-address-section"
        hx-trigger="mahxcheckout-billing-canceled"
        hx-indicator="#billing-address-section-loader"
        hx-include="#is-billing-same, [name=form_key]"
        hx-vals='{"show_form": 0, "show_cards": <?= $eHtmlAttr((int)$viewModel->isCustomerHaveAddresses()) ?> }'
        hx-post="<?= $block->getUrl('mahxcheckout/billing/editBilling') ?>"
    >
        <?= $eHtml(__('Cancel')) ?>
    </button>
    <button class="btn btn-neutral" type="button" @click="handleBillingUpdate"
            hx-swap="outerHTML"
            hx-indicator=".save-billing-loader"
            hx-target="#billing-address-section"
            hx-trigger="mahxcheckout-billing-validated from:body"
            hx-post="<?= $eUrl($block->getUrl('mahxcheckout/billing/billingAddressPost')) ?>"
    >
        <?= $eHtml(__('Update')) ?>
    </button>
</div>
<?php endif; ?>
