<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use MageHx\MahxCheckout\ViewModel\GuestEmail;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var string $nonce */
/** @var Esc $esc */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(GuestEmail::class);
$themeInfo = $viewModelProvider->get(DesignThemeInfo::class);
?>
<script nonce="<?= $esc->html($nonce) ?>">
    'use strict';

    function GuestEmailForm(form) {
        return {
            form: null,
            validator: null,

            init() {
                this.form = form || this.$el;
                this.addValidationToForm();
            },

            addValidationToForm() {
                this.validator = mahxCheckout.validator(Object.assign({
                    form: this.form,
                }, JSON.parse('<?= $esc->js($viewModel->getValidationJson()) ?>')));
                this.addValidatorToPageNavigation(this.form.id, this.validator);
            },
        };
    }
    <?php if ($themeInfo->isHyvaTheme()): ?>
    document.addEventListener('alpine:init', () => {
        Alpine.data('GuestEmailForm', GuestEmailForm);
    });
    <?php endif; ?>
</script>
