<?php

use MageHx\MahxCheckout\ViewModel\GuestEmail;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var string $eHtmlAttr */
/** @var string $nonce */
/** @var Closure $eJs */
/** @var Closure $viewModelProvider */
/** @var GuestEmail $viewModel */

$viewModel = $viewModelProvider(GuestEmail::class);
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        Alpine.data('GuestEmailForm', () => ({
            form: null,
            validator: null,

            init() {
                this.form = this.$el;
                this.addValidationToForm();
            },

            <?php
            /**
             * Email field directly triggers htmx post request as it is bind directly.
             * However, we want to apply frontend validation first and then only need to trigger htmx post request.
             * This is how it is performed
             */
            ?>
            async validate() {
                const isValid = await this.validator.revalidate();
                if (isValid) {
                    htmx.trigger(document.body, 'mahxcheckout-guest-email-form-validated')
                }
            },

            dispatchEmailSavedEvent(event) {
                this.$dispatch('mahxcheckout-email-saved', { htmxEvent: event, form: form });
            },

            addValidationToForm() {
                this.validator = mahxCheckout.validator({
                    form: this.form,
                    rules: JSON.parse('<?= $eJs($viewModel->getValidationJson()) ?>'),
                });
                this.addValidatorToPageNavigation(this.form.id, this.validator);
            },
        }));
    });
</script>
