<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\GuestEmail;

/** @var Template $block */
/** @var string $eHtmlAttr */
/** @var string $nonce */
/** @var Closure $eJs */
/** @var Closure $viewModelProvider */
/** @var GuestEmail $viewModel */
$viewModel = $viewModelProvider(GuestEmail::class);
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        Alpine.data('GuestEmailForm', () => ({
            form: null,
            validator: null,

            init() {
                this.form = this.$el;
                this.addValidationToForm();
            },

            <?php
            /**
             * Email field directly triggers htmx post request as it is bind directly.
             * However, we want to apply frontend validation first and then only need to trigger htmx post request.
             * This is how it is performed
             */
            ?>
            async validate() {
                const isValid = await this.validator.revalidate();
                if (isValid) {
                    htmx.trigger(document.body, 'mahxcheckout-guest-email-form-validated')
                }
            },

            dispatchEmailSavedEvent(event) {
                this.$dispatch('mahxcheckout-email-saved', { htmxEvent: event, form: form });
            },

            addValidationToForm() {
                const validator = mahxCheckout.validator(this.form);
                validator.setValidationRules([{ element: this.form.elements.email, rules: 'required|email' }]);
                this.addValidatorToPageNavigation(this.form.id, validator);
                this.validator = validator;
            },
        }));
    });
</script>
