<?php

use MageHx\HtmxActions\Enums\HtmxSwapOption;
use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\GuestEmail;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var GuestEmail $viewModel */
/** @var HxAttributesRenderer $hxAttrRenderer */

$viewModel = $viewModelProvider(GuestEmail::class);
$hxAttrRenderer = $viewModelProvider(HxAttributesRenderer::class);
?>
<div id="guest-email-form-container">
    <form id="guest-email-form" novalidate="novalidate" x-data="GuestEmailForm">
        <div class="form-control w-full max-w-sm">
            <label class="label" for="gef-email">
                <span class="label-text">
                    <?= $eHtml(__('Email Address')) ?>
                    <span class="text-red-500 ml-1" aria-hidden="true">*</span>
                </span>
            </label>
            <input
                id="gef-email" type="text" name="email" placeholder="joe@example.com"
                class="input input-bordered input-sm w-full max-w-sm" value="<?= $eHtmlAttr($viewModel->getEmail()) ?>"
                @change="validate" @keydown.enter.prevent="validate"
                <?= $hxAttrRenderer->hxBuilder()
                        ->target('#guest-email-form-container')
                        ->swap(HtmxSwapOption::outerHTML)
                        ->trigger('mahxcheckout-guest-email-form-validated from:body')
                        ->post('mahxcheckout/form/guestEmailPost')
                        ->render(); ?>
            />
        </div>
        <?= $formKey ?>
    </form>

    <div class="max-w-xs my-4">
        <div class="divider"></div>
    </div>
</div>
