<?php declare(strict_types=1);

use MageHx\HtmxActions\Enums\HtmxSwapOption;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\GuestEmail;

/** @var Template $block */
/** @var string $nonce */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var GuestEmail $viewModel */
/** @var HxAttributesRenderer $hxAttrRenderer */
/** @var DesignThemeInfo $themeInfo */

$themeInfo = $viewModelProvider(DesignThemeInfo::class);
$viewModel = $viewModelProvider(GuestEmail::class);
$hxAttrRenderer = $viewModelProvider(HxAttributesRenderer::class);
?>
<div id="guest-email-form-container">
    <form id="guest-email-form" class="form form-login" novalidate="novalidate" x-data="GuestEmailForm">
        <fieldset id="customer-email-fieldset" class="fieldset">
            <div class="field _required form-control w-full max-w-lg">
                <label class="label" for="gef-email">
                    <span class="label-text after:content-['*'] after:text-red-500 after:ml-1">
                        <?= $eHtml(__('Email Address')) ?>
                    </span>
                </label>
                <div class="control">
                    <input
                        id="gef-email" type="text" name="email" placeholder="joe@example.com"
                        class="input-text input input-bordered input-sm md:input-md w-full max-w-lg"
                        value="<?= $eHtmlAttr($viewModel->getEmail()) ?>"
                        <?= $hxAttrRenderer->hxBuilder()
                            ->post('mahxcheckout/form/guestEmailPost')
                            ->swapNone()
                            ->validate()
                            ->render(); ?>
                    />
                </div>
            </div>
        </fieldset>
        <?= $formKey ?>
    </form>
    <?php if ($themeInfo->isMagentoTheme()): ?>
        <script nonce="<?= $eHtmlAttr($nonce) ?>">
            'use strict';

            require(['jquery', 'MageHx_MahxCheckout/js/page-navigation'], ($, pageNavigation) => {
                $(() => {
                    const guestForm = document.getElementById('guest-email-form');
                    const guestManager = Object.assign(pageNavigation, GuestEmailForm(guestForm));
                    guestManager.init();
                });
            });
        </script>
    <?php endif; ?>

    <div class="max-w-xs my-4 md:my-8">
        <div class="divider"></div>
    </div>
</div>
