<?php

use MageHx\HtmxActions\Enums\HtmxSwapOption;
use MageHx\MahxCheckout\ViewModel\HxAttributesRenderer;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\GuestEmail;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var GuestEmail $viewModel */
/** @var HxAttributesRenderer $hxAttrRenderer */

$viewModel = $viewModelProvider(GuestEmail::class);
$hxAttrRenderer = $viewModelProvider(HxAttributesRenderer::class);
?>
<div id="guest-email-form-container">
    <form id="guest-email-form" class="form form-login" novalidate="novalidate" x-data="GuestEmailForm">
        <fieldset id="customer-email-fieldset" class="fieldset">
            <div class="field _required form-control w-full max-w-lg">
                <label class="label" for="gef-email">
                    <span class="label-text">
                        <?= $eHtml(__('Email Address')) ?>
                        <span class="text-red-500 ml-1" aria-hidden="true">*</span>
                    </span>
                </label>
                <div class="control">
                    <input
                        id="gef-email" type="text" name="email" placeholder="joe@example.com"
                        class="input-text input input-bordered input-sm md:input-md w-full max-w-lg"
                        value="<?= $eHtmlAttr($viewModel->getEmail()) ?>"
                        <?= $hxAttrRenderer->hxBuilder()
                            ->post('mahxcheckout/form/guestEmailPost')
                            ->swapNone()
                            ->validate()
                            ->render(); ?>
                    />
                </div>
            </div>
        </fieldset>
        <?= $formKey ?>
    </form>

    <div class="max-w-xs my-4 md:my-8">
        <div class="divider"></div>
    </div>
</div>
