<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Header\Logo;
use Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface;

/**
 * @var Logo $block
 * @var Closure $e
 * @var Closure $eUrl
 * @var Escaper $escaper
 * @var LogoSizeResolverInterface|null $logoSizeResolver
 */

$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>
<div class="flex justify-center mt-6">
    <div class="container">
        <a
            class="logo"
            href="<?= $eUrl($block->getUrl('')) ?>"
            title="<?= $escaper->escapeHtmlAttr($storeName) ?>"
            aria-label="store logo">
            <img src="<?= $eUrl($block->getLogoSrc()) ?>"
                 title="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
                 alt="<?= $escaper->escapeHtmlAttr($block->getLogoAlt()) ?>"
                <?= $logoWidth ? 'width="' . $escaper->escapeHtmlAttr($logoWidth) . '"' : '' ?>
                <?= $logoHeight ? 'height="' . $escaper->escapeHtmlAttr($logoHeight) . '"' : '' ?>
            />
        </a>
    </div>
</div>
