<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use Magento\Theme\Block\Html\Header\Logo;
use Magento\Theme\ViewModel\Block\Html\Header\LogoSizeResolverInterface;

/**
 * @var Logo $block
 * @var Esc $esc
 * @var LogoSizeResolverInterface|null $logoSizeResolver
 */

$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>
<div class="flex justify-center mt-6">
    <div class="container">
        <a
            class="logo"
            href="<?= $esc->url($block->getUrl('')) ?>"
            title="<?= $esc->htmlAttr($storeName) ?>"
            aria-label="store logo">
            <img src="<?= $esc->url($block->getLogoSrc()) ?>"
                 title="<?= $esc->htmlAttr($block->getLogoAlt()) ?>"
                 alt="<?= $esc->htmlAttr($block->getLogoAlt()) ?>"
                <?= $logoWidth ? 'width="' . $esc->htmlAttr($logoWidth) . '"' : '' ?>
                <?= $logoHeight ? 'height="' . $esc->htmlAttr($logoHeight) . '"' : '' ?>
            />
        </a>
    </div>
</div>
