<?php declare(strict_types=1);

use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingAddressCards;

/** @var Template $block */
/** @var Esc $esc */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(ShippingAddressCards::class);
$designThemeInfo = $viewModelProvider->get(DesignThemeInfo::class);
?>
<div id="shipping-address-details" class="opc-block-shipping-information collapse collapse-open">
    <div class="ship-to text-xl font-medium border-b collapse-title">
        <div class="shipping-information-title flex items-center justify-between">
            <span><?= $esc->html(__('Ship To:')) ?></span>
            <button
                type="button" class="action-edit btn-edit-pencil"
                hx-target="#checkout-main-content"
                hx-swap="outerHTML"
                hx-indicator="#checkout-page-loader"
                hx-include="[name=form_key]"
                hx-post="<?= $esc->url($block->getUrl('mahxcheckout/step/getStepContent', ['step' => 'shipping'])) ?>"
            >
                <?php if ($designThemeInfo->isHyvaTheme()): ?>
                    <?php // Hero Solid Pencil Svg icon ?>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-6">
                        <path d="M21.731 2.269a2.625 2.625 0 0 0-3.712 0l-1.157 1.157 3.712 3.712 1.157-1.157a2.625 2.625 0 0 0 0-3.712ZM19.513 8.199l-3.712-3.712-12.15 12.15a5.25 5.25 0 0 0-1.32 2.214l-.8 2.685a.75.75 0 0 0 .933.933l2.685-.8a5.25 5.25 0 0 0 2.214-1.32L19.513 8.2Z" />
                    </svg>
                <?php endif; ?>
            </button>
        </div>
    </div>
    <div class="pt-4 collapse-content">
        <div class="space-y-2 text-base italic font-normal">
            <?php $addressLines = $viewModel->getShippingAddressLines(); ?>
            <p class="font-semibold"><?= $esc->html($addressLines->name) ?></p>
            <p><?= $esc->html($addressLines->streetLine1 ?? '') ?></p>
            <p><?= $esc->html($addressLines->streetLine2 ?? '') ?></p>
            <p><?= $esc->html($addressLines->postcode ?? '') ?></p>
            <p><?= $esc->html($addressLines->country ?? '') ?></p>
            <p class="text-blue-600 mt-1"><?= $esc->html($addressLines->telephone ?? '') ?></p>
        </div>
    </div>
</div>
