<?php declare(strict_types=1);

use MageHx\HtmxActions\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\Enum\CheckoutForm;
use MageHx\MahxCheckout\ViewModel\ShippingAddress;
use MageHx\MahxCheckout\ViewModel\ShippingAddressCards;

/** @var Template $block */
/** @var string $nonce */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var ShippingAddressCards $viewModel */
/** @var ShippingAddress $formModel */
/** @var HxAttributesRenderer $hxAttributesRenderer */
/** @var DesignThemeInfo $themeInfo */

$themeInfo = $viewModelProvider(DesignThemeInfo::class);
$viewModel = $viewModelProvider(ShippingAddressCards::class);
$hxAttributesRenderer = $viewModelProvider(HxAttributesRenderer::class);
$formModel = $viewModelProvider(ShippingAddress::class);
$addOOBAttribute = $block->getData('add_oob_attribute');
$newAddressFormName = CheckoutForm::NEW_ADDRESS->value;
?>
<div id="new-shipping-address-container" x-data="NewShippingAddressFormManager">
    <form id="<?= $eHtmlAttr($newAddressFormName) ?>"
        <?= $hxAttributesRenderer->hxBuilder()
            ->post('mahxcheckout/form/saveNewShippingAddress')
            ->target('#shipping-address-cards')
            ->indicator('#shipping-address-cards-loader')
            ->swapOuterHTML()
            ->render(); ?>
    >
        <h2 class="text-xl font-semibold mb-4"><?= $eHtml(__('Add New Address')) ?></h2>

        <div class="fieldset address">
            <?php foreach ($formModel->getAddressFields($newAddressFormName) as $field): ?>
                <?= $formModel->renderField($field) ?>
            <?php endforeach; ?>
            <?= $formKey ?>
        </div>

        <div class="actions-toolbar">
            <div class="actions flex items-center justify-end space-x-4">
                <button
                    class="action action-cancel btn btn-ghost" type="button"
                    <?= $hxAttributesRenderer->hxBuilder()
                        ->post('mahxcheckout/shipping/getShippingAddressCardsContent')
                        ->target('#shipping-address-cards')
                        ->include('[name=form_key]')
                        ->indicator('#shipping-address-cards-loader')
                        ->swapOuterHTML()
                        ->render(); ?>
                >
                    <?= $eHtml(__('Cancel')) ?>
                </button>
                <button class="action action-update btn btn-neutral" type="submit">
                    <?= $eHtml($viewModel->isNewAddressExists() ? __('Ship Here') : __('Update')) ?>
                </button>
            </div>
        </div>
        <?php if ($themeInfo->isMagentoTheme()): ?>
            <script nonce="<?= $eHtmlAttr($nonce) ?>">
                'use strict';

                require(['jquery', 'MageHx_MahxCheckout/js/page-navigation'], ($, pageNavigation) => {
                    $(() => {
                        const containerElem = document.getElementById('new-shipping-address-container');
                        const newAddressManager = Object.assign(pageNavigation, NewShippingAddressFormManager(containerElem));
                        newAddressManager.init();
                    });
                });
            </script>
        <?php endif; ?>
    </form>
</div>
