<?php declare(strict_types=1);

use MageHx\HtmxActions\ViewModel\HxAttributesRenderer;
use MageHx\MageTemplateUtils\Model\Esc;
use MageHx\MageTemplateUtils\Model\ViewModelProvider;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\Enum\CheckoutForm;
use MageHx\MahxCheckout\ViewModel\ShippingAddress;
use MageHx\MahxCheckout\ViewModel\ShippingAddressCards;

/** @var Template $block */
/** @var string $nonce */
/** @var Esc $esc */
/** @var string $formKey */
/** @var ViewModelProvider $viewModelProvider */

$viewModel = $viewModelProvider->get(ShippingAddressCards::class);
$hxAttributesRenderer = $viewModelProvider->get(HxAttributesRenderer::class);
$formModel = $viewModelProvider->get(ShippingAddress::class);
$addOOBAttribute = $block->getData('add_oob_attribute');
$newAddressFormName = CheckoutForm::NEW_ADDRESS->value;
?>
<div id="new-shipping-address-container" x-data="NewShippingAddressFormManager">
    <form id="<?= $esc->htmlAttr($newAddressFormName) ?>"
        <?= $hxAttributesRenderer->hxBuilder()
            ->post('mahxcheckout/form/saveNewShippingAddress')
            ->target('#shipping-address-cards')
            ->indicator('#shipping-address-cards-loader')
            ->swapOuterHTML()
            ->render(); ?>
    >
        <h2 class="text-xl font-semibold mb-4"><?= $esc->html(__('Add New Address')) ?></h2>

        <div class="max-w-lg">
            <div class="fieldset address grid md:grid-cols-4 gap-2">
                <?php foreach ($formModel->getAddressFields($newAddressFormName) as $field): ?>
                    <?= $formModel->renderField($field) ?>
                <?php endforeach; ?>
                <?= $formKey ?>
            </div>
        </div>

        <div class="actions-toolbar max-w-lg">
            <div class="actions flex items-center justify-end space-x-4">
                <button
                    class="action action-cancel btn btn-ghost" type="button"
                    <?= $hxAttributesRenderer->hxBuilder()
                        ->post('mahxcheckout/shipping/getShippingAddressCardsContent')
                        ->target('#shipping-address-cards')
                        ->include('[name=form_key]')
                        ->indicator('#shipping-address-cards-loader')
                        ->swapOuterHTML()
                        ->render(); ?>
                >
                    <?= $esc->html(__('Cancel')) ?>
                </button>
                <button class="action action-update btn btn-neutral" type="submit">
                    <?= $esc->html($viewModel->isNewAddressExists() ? __('Ship Here') : __('Update')) ?>
                </button>
            </div>
        </div>
        <?= $block->getChildHtml('luma_js') ?>
    </form>
</div>
