<?php declare(strict_types=1);

use MageHx\HtmxActions\ViewModel\HxAttributesRenderer;
use MageHx\MahxCheckout\ViewModel\DesignThemeInfo;
use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingAddressCards;

/** @var Template $block */
/** @var string $nonce */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var ShippingAddressCards $viewModel */
/** @var HxAttributesRenderer $hxAttributesRenderer */
/** @var DesignThemeInfo $themeInfo */

$themeInfo = $viewModelProvider(DesignThemeInfo::class);
$viewModel = $viewModelProvider(ShippingAddressCards::class);
$hxAttributesRenderer = $viewModelProvider(HxAttributesRenderer::class);
$estimatePropsJson = htmlspecialchars($viewModel->getNewAddressEstimatePropsJson(), ENT_QUOTES, 'UTF-8');
?>
<div
    id="shipping-address-cards"
    class="relative"
    data-selected-address="<?= $eHtmlAttr($viewModel->getCustomerAddressSelected()) ?>"
    x-data="ShippingAddressCards"
>
    <?= $block->getChildHtml('formTitle') ?>
    <?php
    /**
     * ############### SHIPPING ADDRESS FORM ######################
     * We create shipping address form here in order to pass customer address id as the shipping information.
     * This data will be used when user tries to navigate to next step.
     */
    ?>
    <form id="shipping-address-form">
        <?= $formKey ?>
        <input type="hidden" name="customer_address_id" id="customer_address_id"
               value="<?= $eHtmlAttr($viewModel->getCustomerAddressSelected()) ?>"/>
    </form>
    <?php // ############### SHIPPING ADDRESS FORM - ends ###################### ?>

    <div class="shipping-address-items grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
        <?php foreach ($viewModel->getCustomerAddressCards() as $addressCard): ?>
            <?php $addressLines = $addressCard->addressLines; ?>
            <div
                class="shipping-address-item flex flex-col justify-between p-4 rounded-md shadow bg-white min-h-[260px]"
                data-address-id="<?= $eHtmlAttr($addressCard->addressId) ?>"
                data-role="address-card"
                x-data="AddressCard"
            >
                <template x-if="isSelected">
                    <?php // Tick SVG  ?>
                    <div class="absolute top-0 right-0 bg-orange-500 text-white p-1 rounded-bl-md">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                        </svg>
                    </div>
                </template>

                <div>
                    <p class="font-semibold"><?= $eHtml($addressLines->name) ?></p>
                    <p><?= $eHtml($addressLines->streetLine1 ?? '') ?></p>
                    <p><?= $eHtml($addressLines->streetLine2 ?? '') ?></p>
                    <p><?= $eHtml($addressLines->postcode ?? '') ?></p>
                    <p><?= $eHtml($addressLines->country ?? '') ?></p>
                    <p class="text-blue-600 mt-1"><?= $eHtml($addressLines->telephone ?? '') ?></p>
                </div>

                <?= $block->getChildBlock('actions')->setData('address_card', $addressCard)->toHtml() ?>
            </div>
        <?php endforeach; ?>
    </div>

    <div id="shipping-address-form-section" class="mt-6 pt-6">
        <?php if (!$viewModel->isNewAddressExists()): ?>
            <button
                type="button" class="btn btn-outline btn-sm"
                hx-target="#shipping-address-form-section"
                hx-indicator="#shipping-address-cards-loader"
                hx-get="<?= $block->getUrl("mahxcheckout/shipping/getNewAddressForm") ?>"
            >
                + <?= $eHtml(__('New Address')) ?>
            </button>
        <?php endif; ?>
    </div>

    <?= $block->getChildHtml('loader') ?>

    <?php if ($themeInfo->isMagentoTheme()): ?>
        <script nonce="<?= $eHtmlAttr($nonce) ?>">
            'use strict';

            require(['jquery'], ($) => {
                $(() => {
                    const shippingAddrCards = document.getElementById('shipping-address-cards');
                    const shippingAddrCardsManager = ShippingAddressCards(shippingAddrCards);
                    shippingAddrCardsManager.$store = {
                        shippingAddressCardStorage: ShippingAddressCardStorage,
                    };
                    shippingAddrCardsManager.init();

                    const addressCardsElems = shippingAddrCards.querySelectorAll("[data-role='address-card']");
                    Array.from(addressCardsElems).forEach((cardElem) => {
                        const addressCardManager = AddressCard(cardElem);
                        addressCardManager.$store = {
                            shippingAddressCardStorage: ShippingAddressCardStorage,
                        };
                        addressCardManager.init();
                    });
                });
            });
        </script>
    <?php endif; ?>
</div>

