<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\ViewModel\ShippingAddressCards;

/** @var Template $block */
/** @var Closure $eHtml */
/** @var Closure $eHtmlAttr */
/** @var Closure $eUrl */
/** @var string $formKey */
/** @var Closure $viewModelProvider */
/** @var ShippingAddressCards $viewModel */

$viewModel = $viewModelProvider(ShippingAddressCards::class);
$estimatePropsJson = htmlspecialchars($viewModel->getNewAddressEstimatePropsJson(), ENT_QUOTES, 'UTF-8');
?>
<div
    id="shipping-address-cards-container"
    class="relative"
    data-selected-address="<?= $eHtmlAttr($viewModel->getCustomerAddressSelected()) ?>"
    x-data="ShippingAddressCards"
>
    <?= $block->getChildHtml('formTitle') ?>
    <?php
    /**
     * ############### SHIPPING ADDRESS FORM ######################
     * We create shipping address form here in order to pass customer address id as the shipping information.
     * This data will be used when user tries to navigate to next step.
     */
    ?>
    <form id="shipping-address-form">
        <?= $formKey ?>
        <input type="hidden" name="customer_address_id" id="customer_address_id" :value="selectedAddressId" />
    </form>
    <?php // ############### SHIPPING ADDRESS FORM - ends ###################### ?>

    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
        <?php foreach ($viewModel->getCustomerAddressCards() as $addressCard): ?>
            <?php
                $addressId = $addressCard['addressId'];
                $isNewAddress = $addressId === 'new';
                $isAddressSelected = $addressCard['isSelected'];
                $addressLines = $addressCard['addressLines'];
            ?>
            <div
                class="flex flex-col justify-between p-4 rounded-md shadow bg-white min-h-[260px]"
                data-address-id="<?= $eHtmlAttr($addressId) ?>"
                x-data="AddressCard"
                :class="addressCardExtraClasses"
            >
                <template x-if="isSelected">
                    <?php // Tick SVG  ?>
                    <div class="absolute top-0 right-0 bg-orange-500 text-white p-1 rounded-bl-md">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                        </svg>
                    </div>
                </template>

                <div>
                    <p class="font-semibold"><?= $eHtmlAttr($addressLines['name']) ?></p>
                    <p><?= $eHtml($addressLines['line_1'] ?? '') ?></p>
                    <p><?= $eHtml($addressLines['line_2'] ?? '') ?></p>
                    <p><?= $eHtml($addressLines['postcode'] ?? '') ?></p>
                    <p><?= $eHtml($addressLines['country'] ?? '') ?></p>
                    <p class="text-blue-600 mt-1"><?= $eHtml($addressLines['telephone'] ?? '') ?></p>
                </div>

                <div class="actions flex items-center min-h-[2.5rem]">
                    <?php if ($isNewAddress): ?>
                        <button
                            class="btn btn-ghost mt-4 text-primary" type="button"
                            hx-target="#shipping-address-form-section"
                            hx-indicator="#shipping-address-cards-loader"
                            hx-get="<?= $block->getUrl("mahxcheckout/shipping/getNewAddressForm") ?>"
                        >
                            <?= $eHtml(__('Edit')) ?>
                        </button>
                    <?php endif; ?>
                    <div class="action-item ml-auto">
                        <button
                            type="button" class="btn btn-sm mt-4"
                            data-id="<?= $eHtmlAttr($addressId) ?>"
                            x-cloak
                            x-show="isNotSelected"
                            @click="setShipToAddress"
                            hx-post="<?= $eUrl($viewModel->getEstimateShippingByAddressIdUrl($addressId)) ?>"
                            hx-trigger="mahxcheckout-customer-address-<?= $eHtmlAttr($addressId) ?>-selected from:window"
                            hx-target="#shipping-methods-section"
                            hx-swap="outerHTML"
                            hx-indicator="#shipping-loader"
                            hx-include="[name=form_key]"
                            <?php if ($isNewAddress): ?>
                                hx-vals='<?= $estimatePropsJson ?>'
                            <?php endif; ?>
                        >
                            <?= $eHtml(__('Ship Here')) ?>
                        </button>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

        <div id="shipping-address-form-section" class="mt-6 pt-6">
            <?php if (!$viewModel->isNewAddressExists()): ?>
                <button
                    type="button" class="btn btn-outline btn-sm"
                    hx-target="#shipping-address-form-section"
                    hx-indicator="#shipping-address-cards-loader"
                    hx-get="<?= $block->getUrl("mahxcheckout/shipping/getNewAddressForm") ?>"
                >
                    + <?= $eHtml(__('New Address')) ?>
                </button>
            <?php endif; ?>
        </div>
    <div id="shipping-address-cards-loader"
         class="htmx-indicator absolute inset-0 flex items-center justify-center bg-white/50 pointer-events-none">
        <span class="loading loading-dots loading-lg"></span>
        <span class="loading loading-dots loading-lg"></span>
        <span class="loading loading-dots loading-lg"></span>
    </div>
</div>

