<?php

use Magento\Framework\View\Element\Template;
use MageHx\MahxCheckout\Enum\CheckoutForm;
use MageHx\MahxCheckout\ViewModel\ShippingAddress;

/** @var Template $block */
/** @var string $eHtmlAttr */
/** @var string $nonce */
/** @var Closure $eJs */
/** @var Closure $eUrl */
/** @var Closure $viewModelProvider */
/** @var ShippingAddress $viewModel */
$viewModel = $viewModelProvider(ShippingAddress::class);
?>
<script nonce="<?= $eHtmlAttr($nonce) ?>">
    document.addEventListener('alpine:init', () => {
        Alpine.data('NewAddressFormManager', () => {
            const newFormId = '<?= $eJs(CheckoutForm::NEW_ADDRESS->value) ?>';

            return {
                form: null,
                validator: null,

                init() {
                    this.form = this.$el.querySelector('form');
                    this.modifyFormAfterRender();
                },

                handleCountryChange(event) {
                    this.$dispatch(`mahxcheckout-${newFormId}-country_id-changed`, { country: event.target.value })
                },

                modifyFormAfterRender() {
                    this.$nextTick(() => {
                        this.focusOnFirstname();
                        this.applyValidation();
                    });
                },

                focusOnFirstname() {
                    this.form.elements.firstname.focus();
                },

                applyValidation() {
                    this.validator = mahxCheckout.validator(Object.assign({
                        form: this.form,
                    }, JSON.parse('<?= $eJs($viewModel->getValidationJson()) ?>')));
                    this.addValidatorToPageNavigation(this.form.id, this.validator);
                },
            };
        });
    });
</script>
